# Generated by Django 3.1.7 on 2021-02-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrados',
            new_name='Registrado',
        ),
    ]
